# [参考](https://github.com/openzipkin/docker-zipkin/blob/master/docker-compose.yml)
version: '3'

services:
  
  redis:
    image: redis:5.0.5
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - 6379:6379
    networks:
      - net
    restart: unless-stopped

volumes:
  redis_data:
networks:
  net:
